ALTER TABLE clients
ALTER COLUMN email DROP NOT NULL,
ALTER COLUMN contact DROP NOT NULL,
ALTER COLUMN address DROP NOT NULL,
ALTER COLUMN date_of_birth DROP NOT NULL,
ALTER COLUMN gender DROP NOT NULL,
ALTER COLUMN nationality DROP NOT NULL;